spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server

logging:
  level:
    root: info


